name: take_health
description: "Take Health - AI powered health platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  dio: ^5.9.2
  equatable: ^2.0.8
  get_it: ^9.2.1
  flutter_web_auth_2: ^5.0.2
  webview_flutter: ^4.13.1
  google_sign_in: ^7.2.0
  go_router: ^17.2.3
  flutter_secure_storage: ^10.2.0
  shared_preferences: ^2.5.5
  logger: ^2.5.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
